/*
 * OpenAPIDefinition annotation is required only once in a project
 *  ### markdown is supported</br> ---
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ApiError;
import io.swagger.client.model.Banana;
import io.swagger.client.model.CreateBanana;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BananasApi
 */
@Ignore
public class BananasApiTest {

    private final BananasApi api = new BananasApi();

    /**
     * create a banana
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createBananaTest() throws ApiException {
        CreateBanana body = null;
        api.createBanana(body);

        // TODO: test validations
    }
    /**
     * get a banana
     *
     * ### markdown is supported&lt;/br&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBananaTest() throws ApiException {
        String id = null;
        Banana response = api.getBanana(id);

        // TODO: test validations
    }
}
