/**
 * OpenAPIDefinition annotation is required only once in a project
 *  ### markdown is supported</br> ---
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param color 
 * @param price price in USD
 * @param id UUID
 * @param nickname 
 */
data class Banana (

    val color: Banana.Color? = null,
    /* price in USD */
    val price: kotlin.Double? = null,
    /* UUID */
    val id: kotlin.String? = null,
    val nickname: kotlin.String? = null
) {
    /**
    * 
    * Values: gREEN,yELLOW,bROWN
    */
    enum class Color(val value: kotlin.String){
        gREEN("GREEN"),
        yELLOW("YELLOW"),
        bROWN("BROWN");
    }
}