/**
 * OpenAPIDefinition annotation is required only once in a project
 *  ### markdown is supported</br> ---
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param color 
 * @param price price in USD
 */
data class CreateBanana (

    val color: kotlin.String? = null,
    /* price in USD */
    val price: kotlin.Double? = null
) {
}