/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bananas.service

import kotlin.test.Test
import kotlin.test.assertTrue
import kotlin.test.fail

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        fail()
    }
}
