/*
 * OpenAPIDefinition annotation is required only once in a project
 *  ### markdown is supported</br> ---
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * CreateBanana
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-24T20:48:54.388+03:00[Asia/Jerusalem]")public class CreateBanana {

  @SerializedName("color")
  private String color = null;

  @SerializedName("price")
  private Double price = null;
  public CreateBanana color(String color) {
    this.color = color;
    return this;
  }

  

  /**
  * Get color
  * @return color
  **/
  @Schema(description = "")
  public String getColor() {
    return color;
  }
  public void setColor(String color) {
    this.color = color;
  }
  public CreateBanana price(Double price) {
    this.price = price;
    return this;
  }

  

  /**
  * price in USD
  * maximum: 256
  * @return price
  **/
  @Schema(example = "5", description = "price in USD")
  public Double getPrice() {
    return price;
  }
  public void setPrice(Double price) {
    this.price = price;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBanana createBanana = (CreateBanana) o;
    return Objects.equals(this.color, createBanana.color) &&
        Objects.equals(this.price, createBanana.price);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(color, price);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBanana {\n");
    
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
